#[derive(Debug, Clone, Copy)]
pub struct OAuthProviderDef {
    pub id: &'static str,
    pub name: &'static str,
    pub env_prefix: &'static str,
    pub oauth_supported: bool,
    pub auth_url: &'static str,
    pub token_url: &'static str,
    pub scopes: &'static str,
    pub use_pkce: bool,
    pub pkce_omit_client_secret: bool,
    pub token_basic_auth: bool,
    pub listening_sync: bool,
    pub revoke_on_disconnect: bool,
    pub revoke_url: &'static str,
    pub extra_auth_params: &'static [(&'static str, &'static str)],
}

const OFF: (bool, bool, bool, bool, bool, bool, &'static str) =
    (false, false, false, false, false, false, "");

pub const PROVIDERS: &[OAuthProviderDef] = &[
    OAuthProviderDef {
        id: "spotify",
        name: "Spotify",
        env_prefix: "SPOTIFY",
        oauth_supported: true,
        auth_url: "https://accounts.spotify.com/authorize",
        token_url: "https://accounts.spotify.com/api/token",
        scopes: "user-read-currently-playing user-read-playback-state",
        use_pkce: true,
        pkce_omit_client_secret: true,
        token_basic_auth: false,
        listening_sync: true,
        revoke_on_disconnect: true,
        revoke_url: "https://accounts.spotify.com/api/token/revoke",
        extra_auth_params: &[("show_dialog", "true")],
    },
    OAuthProviderDef {
        id: "youtube",
        name: "YouTube",
        env_prefix: "YOUTUBE",
        oauth_supported: true,
        auth_url: "https://accounts.google.com/o/oauth2/v2/auth",
        token_url: "https://oauth2.googleapis.com/token",
        scopes: "openid profile https://www.googleapis.com/auth/youtube.readonly",
        use_pkce: true,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[("access_type", "offline"), ("prompt", "consent")],
    },
    OAuthProviderDef {
        id: "tiktok",
        name: "TikTok",
        env_prefix: "TIKTOK",
        oauth_supported: true,
        auth_url: "https://www.tiktok.com/v2/auth/authorize/",
        token_url: "https://open.tiktokapis.com/v2/oauth/token/",
        scopes: "user.info.basic",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "kick",
        name: "Kick",
        env_prefix: "KICK",
        oauth_supported: false,
        auth_url: "",
        token_url: "",
        scopes: "",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "twitch",
        name: "Twitch",
        env_prefix: "TWITCH",
        oauth_supported: true,
        auth_url: "https://id.twitch.tv/oauth2/authorize",
        token_url: "https://id.twitch.tv/oauth2/token",
        scopes: "user:read:email",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "github",
        name: "GitHub",
        env_prefix: "GITHUB",
        oauth_supported: true,
        auth_url: "https://github.com/login/oauth/authorize",
        token_url: "https://github.com/login/oauth/access_token",
        scopes: "read:user",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "steam",
        name: "Steam",
        env_prefix: "STEAM",
        oauth_supported: false,
        auth_url: "",
        token_url: "",
        scopes: "",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "reddit",
        name: "Reddit",
        env_prefix: "REDDIT",
        oauth_supported: true,
        auth_url: "https://www.reddit.com/api/v1/authorize",
        token_url: "https://www.reddit.com/api/v1/access_token",
        scopes: "identity",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: true,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[("duration", "permanent")],
    },
    OAuthProviderDef {
        id: "twitter",
        name: "X",
        env_prefix: "TWITTER",
        oauth_supported: true,
        auth_url: "https://twitter.com/i/oauth2/authorize",
        token_url: "https://api.twitter.com/2/oauth2/token",
        scopes: "users.read tweet.read offline.access",
        use_pkce: true,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: true,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "playstation",
        name: "PlayStation",
        env_prefix: "PLAYSTATION",
        oauth_supported: false,
        auth_url: "",
        token_url: "",
        scopes: "",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "xbox",
        name: "Xbox",
        env_prefix: "XBOX",
        oauth_supported: true,
        auth_url: "https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize",
        token_url: "https://login.microsoftonline.com/consumers/oauth2/v2.0/token",
        scopes: "XboxLive.signin offline_access",
        use_pkce: true,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "epic",
        name: "Epic Games",
        env_prefix: "EPIC",
        oauth_supported: true,
        auth_url: "https://www.epicgames.com/id/authorize",
        token_url: "https://api.epicgames.dev/epic/oauth/v2/token",
        scopes: "basic_profile",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: true,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "paypal",
        name: "PayPal",
        env_prefix: "PAYPAL",
        oauth_supported: true,
        auth_url: "https://www.paypal.com/signin/authorize",
        token_url: "https://api-m.paypal.com/v1/oauth2/token",
        scopes: "openid profile email",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: true,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "riot",
        name: "Riot Games",
        env_prefix: "RIOT",
        oauth_supported: true,
        auth_url: "https://auth.riotgames.com/authorize",
        token_url: "https://auth.riotgames.com/token",
        scopes: "openid offline_access",
        use_pkce: true,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: OFF.1,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
    OAuthProviderDef {
        id: "ebay",
        name: "eBay",
        env_prefix: "EBAY",
        oauth_supported: true,
        auth_url: "https://auth.ebay.com/oauth2/authorize",
        token_url: "https://api.ebay.com/identity/v1/oauth2/token",
        scopes: "https://api.ebay.com/oauth/api_scope",
        use_pkce: false,
        pkce_omit_client_secret: OFF.0,
        token_basic_auth: true,
        listening_sync: OFF.2,
        revoke_on_disconnect: OFF.3,
        revoke_url: OFF.6,
        extra_auth_params: &[],
    },
];

pub fn find_provider(id: &str) -> Option<&'static OAuthProviderDef> {
    PROVIDERS.iter().find(|p| p.id == id)
}

pub fn provider_enabled(def: &OAuthProviderDef) -> bool {
    if !def.oauth_supported {
        return false;
    }
    super::oauth::provider_credentials(def).is_some()
}
